# Google Cloud Build Configuration for Containerizing Application
steps:
# Build the frontend container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-frontend:$SHORT_SHA', './frontend']

# Build the backend container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA', './backend']

# Push the container images to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-frontend:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA']

# Set up kubectl credentials
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'todo-frontend'
  - 'frontend=gcr.io/$PROJECT_ID/todo-frontend:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=todo-app-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'todo-backend'
  - 'backend=gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=todo-app-cluster'

images:
- 'gcr.io/$PROJECT_ID/todo-frontend:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA'