apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=  # "admin" in base64
  admin-password: cHJvbS1vcGVyYXRvcg==  # "prom-operator" in base64